### PR TITLE
KBC-2578 Allow reading deleted project detail using application token

### PR DESCRIPTION
**Pull request by tomasfejfar**
Jira: KBC-2578
Connection PR: https://github.com/keboola/connection/pull/3683

Before asking for review make sure that:

- [x] New client method(s) has tests
- [x] Apiary file is updated
- [x] You declared if there is a BC break or not (will affect next release of a client)

---

### CODE REVIEW

**Review by fejjo — APPROVED** [review]
👍  zmenil som ti tu este ten base na tu branch predtym

**Review by fejjo — CHANGES_REQUESTED** [review]
este by som pridal info do apiary ze to ide zavoalt aj tokenom so scope tak ako to je v predchadzajucom PR

**Comment by tomasfejfar** [comment]
Fixnuto. 

image

**Review by fejjo — COMMENTED** [review]
👌

**Review by fejjo — APPROVED** [review]
omylom som dal len komentar

**Pull request merged**
